name: First Workflow
on: 
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: email notofication
        uses: cinotify/github-action@main
        with:
         to: 'sandeshec042@gmail.com'
         subject: 'building main'
         body: 'This is a notification from GitHub actions.'

